changed SessionTest.testSessionRegisteredCorrectly() to ignore NoClassDefFoundError which is only thrown when testing in Eclipse
git-svn-id: http://svn.code.sf.net/p/quickfixj/code/trunk@1169 40aee5e9-8910-4a9f-ab63-41bea6217522